blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/altus4/altus4/wiki
    about: Check the documentation for usage guides and API reference
  - name: Discussions
    url: https://github.com/altus4/altus4/discussions
    about: Ask questions and discuss ideas with the community
