services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: altus4-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password_here
      MYSQL_DATABASE: altus4_metadata
      MYSQL_USER: altus4_user
      MYSQL_PASSWORD: your_secure_password_here
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - altus4-network
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: altus4-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - altus4-network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      timeout: 10s
      retries: 5

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  altus4-network:
    driver: bridge
